spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://user-service-silly-ratel.apps.apbg.apcf.io}/uaa/user
    client:
      client-id: acme
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://10.0.9.36:3306/service_instance_db?useSSL=false
    username: 9c9e1a9a6f084802acfee5afd7a21e25
    password: jviuonly2hbmwcz1
    initialize: true
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://user-service-shiny-bat.apps.apbg.apcf.io/}/uaa/user
    client:
      client-id: acme
      access-token-uri: http://online-store-web.apps.apbg.apcf.io
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://discovery-service-optimistic-rabbit.apps.apbg.apcf.io/}
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:0.0.0.0}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  application:
    name: account-service
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
