spring.profiles.active: development
---
spring:
  profiles: cloud
  neo4j:
    #host: ${SPRING_NEO4J_HOST:hobby-aeepccdbbpcagbkeoegkneal.dbs.graphenedb.com}
    #port: ${SPRING_NEO4J_PORT:24780}
    host: hobby-aeepccdbbpcagbkeoegkneal.dbs.graphenedb.com
    port: 24780
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://discovery-service-sleepy-gerenuk.apps.apbg.apcf.io}/eureka/
---
spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:127.0.0.1}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:neo4j}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:127.0.0.1}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  client:
    enabled: false
